/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import bll.BLL_NhaCungCap;
import et.ET_NhaCungCap;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import bll.BLL_LoaiDocGia;
import et.ET_LoaiDocGia;

/**
 *
 * @author yushu
 */
public class frmLoaiDocGia extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmLoaiDocGia
     */
    private BLL_LoaiDocGia bll;

    public frmLoaiDocGia() throws Exception {
        initComponents();
        bll = new BLL_LoaiDocGia();
        reset();
    }

    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiDocGia.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã Loại");
        model.addColumn("Tên loại");
        model.addColumn("SL sách giới hạn");
        model.addColumn("Phí");
        tblLoaiDocGia.setModel(model);
    }

    public void hienThiLoaiDG() throws SQLException, Exception {
        ResultSet rs = bll.layDS();
        DefaultTableModel model = (DefaultTableModel) tblLoaiDocGia.getModel();
        model.setNumRows(0);
        while (rs.next()) {
            Object[] col = new Object[4];
            for (int i = 1; i <= 4; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
    }

    public boolean checkSo(String so) {
        if (so.length() == 0) {
            return false;
        }
        char[] c = so.toCharArray();
        for (int i = 0; i < c.length; i++) {
            if (!Character.isDigit(c[i])) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Phí = new javax.swing.JLabel();
        txtPhi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiDocGia = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên loại độc giả");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtTenLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtTenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 76, 176, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LOẠI ĐỘC GIẢ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Phí.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phí.setText("Phí");
        jPanel1.add(Phí, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtPhi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 176, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_26px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_26px.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, -1));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_remove_26px_1.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 100, -1));

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_26px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        tblLoaiDocGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblLoaiDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoaiDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiDocGiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLoaiDocGia);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 690, 180));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số lượng tối đa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        txtSL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 182, -1));

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_new_26px_4.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        if (txtTenLoai.getText().compareTo("") != 0) {
            if (checkSo(txtSL.getText())) {
                if (checkSo(txtPhi.getText())) {
                    String tenLoai = txtTenLoai.getText();
                    int phi = Integer.parseInt(txtPhi.getText());
                    int sl = Integer.parseInt(txtSL.getText());
                    ET_LoaiDocGia et = new ET_LoaiDocGia(0, tenLoai, sl, phi);
                    try {
                        if (bll.themLoai(et)) {
                            JOptionPane.showMessageDialog(rootPane, "Thành công");
                            reset();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Không thành công");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmLoaiDocGia.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Phí không hợp lệ");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Số lượng không hợp lệ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (txtTenLoai.getText().compareTo("") != 0) {
            if (checkSo(txtSL.getText())) {
                if (checkSo(txtPhi.getText())) {
                    int row = tblLoaiDocGia.getSelectedRow();
                    int maLoai = Integer.parseInt(tblLoaiDocGia.getValueAt(row, 0).toString());
                    String tenLoai = txtTenLoai.getText();
                    int phi = Integer.parseInt(txtPhi.getText());
                    int sl = Integer.parseInt(txtSL.getText());
                    ET_LoaiDocGia et = new ET_LoaiDocGia(maLoai, tenLoai, sl, phi);
                    try {
                        if (bll.suaLoai(et)) {
                            JOptionPane.showMessageDialog(rootPane, "Sửa Thành công");
                            reset();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Sửa không thành công");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmLoaiDocGia.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Phí không hợp lệ");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Số lượng không hợp lệ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        int row = tblLoaiDocGia.getSelectedRow();
        if (row != -1) {
            try {
                int maLoai = Integer.parseInt(tblLoaiDocGia.getValueAt(row, 0).toString());
                if (bll.xoaLoai(maLoai)) {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    reset();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa không thành công");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhà cung cấp");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblLoaiDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiDocGiaMouseClicked
        // TODO add your handling code here:
        int row = tblLoaiDocGia.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblLoaiDocGia.getModel();
        txtTenLoai.setText(model.getValueAt(row, 1).toString());
        txtSL.setText(model.getValueAt(row, 2).toString());
        txtPhi.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblLoaiDocGiaMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            // TODO add your handling code here:
            reset();
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_btnMoiActionPerformed
    private void reset() throws Exception {
        txtTenLoai.setText("");
        txtSL.setText("");
        txtPhi.setText("");
        hienThi();
        hienThiLoaiDG();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Phí;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLoaiDocGia;
    private javax.swing.JTextField txtPhi;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
