/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.BLL_DanhMuc;
import bll.BLL_NgonNgu;
import bll.BLL_NXB;
import bll.BLL_Sach;
import bll.BLL_TacGia;
import bll.BLL_ChiTietHD;
import bll.BLL_HoaDon;
import bll.BLL_NhaCungCap;
import bll.BLL_NhanVien;
import et.ET_ChiTietHD;
import et.ET_HoaDon;
import et.ET_Sach;
import et.ET_TacGia;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author LENOVO
 */
public class frmNhapSach extends javax.swing.JFrame {

    /**
     * Creates new form FormNhapSach
     */
    private BLL_Sach bll;
    private BLL_DanhMuc bllDM;
    private BLL_NXB bllNXB;
    private BLL_NgonNgu bllNN;
    private BLL_TacGia bllTD;
    private BLL_NhanVien bllNV;
    private BLL_HoaDon bllHD;
    private BLL_NhaCungCap bllNCC;
    private BLL_ChiTietHD bllCTHH;
    private int STT = 0;

    public frmNhapSach() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        bllDM = new BLL_DanhMuc();
        bllNXB = new BLL_NXB();
        bllNN = new BLL_NgonNgu();
        bllTD = new BLL_TacGia();
        bll = new BLL_Sach();
        bllHD = new BLL_HoaDon();
        bllNCC = new BLL_NhaCungCap();
        AutoCompleteDecorator.decorate(cbbDM);
        AutoCompleteDecorator.decorate(cbbNN);
        AutoCompleteDecorator.decorate(cbbNXB);
        AutoCompleteDecorator.decorate(cbbNCC);
        comboboxDM();
        comboboxNN();
        comboboxNXB();
        comboboxNCC();
        hienThi();
        hienThiSach();
    }

    public String themTD(String Ten) throws Exception {
        ResultSet rs = bllTD.layDS();
        rs.last();
        int row = rs.getRow();
        if (row == 0) {
            STT = 1;
        } else {
            rs.beforeFirst();
            while (rs.next()) {
                STT = Integer.parseInt(rs.getObject(1).toString().substring(2)) + 1;
            }
        }
        String ma = String.format("%02d", STT);
        String New = ("TD" + ma);
        ET_TacGia TD = new ET_TacGia(New, Ten);
        bllTD.themTD(TD);
        return New;
    }

    public String themCTHH() throws Exception {
        ResultSet rs = bllCTHH.layDS();
        JOptionPane.showConfirmDialog(cbbNN, "hehe");
        rs.last();
        JOptionPane.showConfirmDialog(cbbNN, "last");
        int row = rs.getRow();
        if (row == 0) {
            STT = 1;
            JOptionPane.showConfirmDialog(cbbNN, "true");
        } else {
            JOptionPane.showConfirmDialog(cbbNN, "false");
            rs.beforeFirst();
            while (rs.next()) {
                STT = Integer.parseInt(rs.getObject(1).toString().substring(2)) + 1;
            }
        }
        String ma = String.format("%02d", STT);
        String New = ("CT" + ma);
        return New;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamXB = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDS = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        cbbNCC = new javax.swing.JComboBox<>();
        txtSoTrang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbbDM = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNV = new javax.swing.JTextField();
        cbbNXB = new javax.swing.JComboBox<>();
        txtGia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbbNN = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 177, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamXB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtNamXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 150, -1));

        btnthem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_26px.png"))); // NOI18N
        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel1.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_26px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Giá:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Năm xuất bản:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, -1));

        txtMaHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Tác giả:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tên NXB:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Số lượng:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, 26));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Tên sách:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 150, -1));

        jPanel2.setBackground(new java.awt.Color(84, 101, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NHẬP SÁCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 995, -1));

        txtTenSach.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Mã hoá đơn:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 150, -1));

        tblDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDS);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 460, 990, 240));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Danh Mục:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        cbbNCC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(cbbNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 150, -1));

        txtSoTrang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtSoTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 150, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Số Trang:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        cbbDM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(cbbDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Mã sách:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtMaSach.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Nhân Viên:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, 26));

        txtNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 150, -1));

        cbbNXB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(cbbNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 150, -1));

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Nhà cung cấp:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        cbbNN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(cbbNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Ngôn ngữ:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        String gia = txtGia.getText();
        String ten = txtTenSach.getText();
        String mahd = txtMaHD.getText();
        String maSach = txtMaSach.getText();
        String nv = txtNV.getText();
        String nxb = txtNamXB.getText();
        String sl = txtSoLuong.getText();
        String st = txtSoTrang.getText();
        String maTD = txtTacGia.getText();
        if (maTD.compareTo("") == 0 || gia.compareTo("") == 0 || ten.compareTo("") == 0 || mahd.compareTo("") == 0 || maSach.compareTo("") == 0 || nv.compareTo("") == 0 || nxb.compareTo("") == 0 || sl.compareTo("") == 0 || st.compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        } else {
            try {
                String tenDM = cbbDM.getSelectedItem().toString();
                String tenNXB = cbbNXB.getSelectedItem().toString();
                String tenNN = cbbNN.getSelectedItem().toString();
                String tenNCC = cbbNCC.getSelectedItem().toString();
                String maDM = bllDM.layMa(tenDM);
                String maNXB = bllNXB.layMa(tenNXB);
                String maNN = bllNN.layMa(tenNN);
                String maNCC = bllNCC.layMa(tenNCC);
                if (bllHD.checkTonTai(mahd)) {
                    JOptionPane.showMessageDialog(null, "Mã hoá đơn đã tồn tại");
                } else {
//                    JOptionPane.showMessageDialog(null, nv);
//                    if (bllNV.checkTT(nv)) {
//                        JOptionPane.showMessageDialog(null, "NV đơn đã tồn tại");
                        if (bllTD.checkTonTai(maTD)) {
                            maTD = bllTD.layMa(maTD);
                        } else {
                            maTD = themTD(txtTacGia.getText());
                        }
                        if (bll.checkTonTai(txtMaSach.getText()) == true) {
                            int tong = bll.laySLSach(txtMaSach.getText()) + Integer.parseInt(txtSoLuong.getText());
                            ET_Sach et = new ET_Sach(maSach, ten, tong, Integer.parseInt(gia), Integer.parseInt(nxb), Integer.parseInt(st), maTD, maNXB, maDM, maNN);
                            ET_HoaDon HDon = new ET_HoaDon(mahd, nv, maNCC);
                            String maCT = themCTHH();
                            ET_ChiTietHD CT = new ET_ChiTietHD(maCT, Integer.parseInt(sl), maNCC, maSach);
                            bllHD.themHoaDon(HDon);
                            bllCTHH.themChiTietHD(CT);
                            try {
                                if (bll.suaSach(et)) {
                                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                                } else {
                                    JOptionPane.showMessageDialog(null, "Thêm không thành công");
                                }
                                hienThiSach();
                            } catch (SQLException ex) {
                                Logger.getLogger(frmNhapSach.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            ET_Sach et = new ET_Sach(maSach, ten, Integer.parseInt(sl), Integer.parseInt(gia), Integer.parseInt(nxb), Integer.parseInt(st), maTD, maNXB, maDM, maNN);
                            ET_HoaDon HDon = new ET_HoaDon(mahd, nv, maNCC);
                            String maCT = themCTHH();
                            ET_ChiTietHD CT = new ET_ChiTietHD(maCT, Integer.parseInt(sl), maNCC, maSach);
                            bllHD.themHoaDon(HDon);
                            bllCTHH.themChiTietHD(CT);
                            try {
                                if (bll.themSach(et)) {
                                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
                                }
                                hienThiSach();
                            } catch (SQLException ex) {
                                Logger.getLogger(frmNhapSach.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại");
//                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(frmNhapSach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmNhapSach().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmNhapSach.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblDS.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã Sách");
        model.addColumn("Tên Sách");
        model.addColumn("Số Lượng");
        model.addColumn("Giá");
        model.addColumn("Năm Xuất Bản");
        model.addColumn("Số Trang");
        model.addColumn("Tác Giả");
        model.addColumn("NXB");
        model.addColumn("Thể Loại");
        model.addColumn("Ngôn Ngữ");
        model.addColumn("Ngày Nhập");
        tblDS.setModel(model);

    }

    public void comboboxDM() throws Exception {
        bllDM = new BLL_DanhMuc();
        cbbDM.removeAllItems();
        ResultSet rs = bllDM.layDM();
        while (rs.next()) {
            cbbDM.addItem(rs.getString("name"));
        }
    }

    public void comboboxNXB() throws Exception {
        bllNXB = new BLL_NXB();
        cbbNXB.removeAllItems();
        ResultSet rs = bllNXB.layDS();
        while (rs.next()) {
            cbbNXB.addItem(rs.getString("name"));
        }
    }

    public void comboboxNN() throws Exception {
        bllNN = new BLL_NgonNgu();
        cbbNN.removeAllItems();
        ResultSet rs = bllNN.layNgonNgu();
        while (rs.next()) {
            cbbNN.addItem(rs.getString("name"));
        }
    }
    public void comboboxNCC() throws Exception {
        bllNCC = new BLL_NhaCungCap();
        cbbNCC.removeAllItems();
        ResultSet rs = bllNCC.layNCC();
        while (rs.next()) {
            cbbNCC.addItem(rs.getString("supplier_name"));
        }
    }

    public void hienThiSach() throws SQLException, Exception {
        ResultSet rs = bll.layDS();
        DefaultTableModel model = (DefaultTableModel) tblDS.getModel();
        model.setNumRows(0);
        while (rs.next()) {
            Object[] col = new Object[11];
            for (int i = 1; i <= 11; i++) {
                if (i == 7) {
                    col[i - 1] = bllTD.layTen(rs.getObject(i).toString());
                } else if (i == 8) {
                    col[i - 1] = bllNXB.layTen(rs.getObject(i).toString());
                } else if (i == 9) {
                    col[i - 1] = bllDM.layTen(rs.getObject(i).toString());
                } else if (i == 10) {
                    col[i - 1] = bllNN.layTen(rs.getObject(i).toString());
                } else {
                    col[i - 1] = rs.getObject(i);
                }
            }
            model.addRow(col);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnthem;
    private javax.swing.JComboBox<String> cbbDM;
    private javax.swing.JComboBox<String> cbbNCC;
    private javax.swing.JComboBox<String> cbbNN;
    private javax.swing.JComboBox<String> cbbNXB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDS;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNV;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
