/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
import et.ET_NgonNgu;
import java.util.Date;
import bll.BLL_NgonNgu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author yushu
 */
public class frmNgonNgu extends javax.swing.JFrame {

    private BLL_NgonNgu bll;
    private int STT = 0;

    /**
     * Creates new form frmNN
     */
    public frmNgonNgu() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        bll = new BLL_NgonNgu();
        reset();
        txtMaNgonNgu.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaNgonNgu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenNgonNgu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNgonNgu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 177, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mã ngôn ngữ:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 117, -1, -1));

        txtMaNgonNgu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtMaNgonNgu, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 114, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên ngôn ngữ:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 117, -1, -1));

        txtTenNgonNgu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTenNgonNgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNgonNguActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenNgonNgu, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 114, 182, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_26px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_26px.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, -1));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_remove_26px_1.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 100, -1));

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_26px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        tblNgonNgu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblNgonNgu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã ngôn ngữ", "Tên ngôn ngữ"
            }
        ));
        jScrollPane2.setViewportView(tblNgonNgu);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 700, 190));

        jPanel2.setBackground(new java.awt.Color(84, 101, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NGÔN NGỮ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_new_26px_4.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNgonNguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNgonNguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNgonNguActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String maNgonNgu = txtMaNgonNgu.getText();
        String tenNgonNgu = txtTenNgonNgu.getText();
        ET_NgonNgu et = new ET_NgonNgu(maNgonNgu, tenNgonNgu);
        if (maNgonNgu == "" || tenNgonNgu == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                if (bll.checkNN(maNgonNgu)) {
                    JOptionPane.showMessageDialog(null, "Đã tồn tại ngôn ngữ");
                } else {
                    et = new ET_NgonNgu(maNgonNgu, tenNgonNgu);
                    if (bll.themNgonNgu(et)) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                        reset();
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String maNgonNgu = txtMaNgonNgu.getText();
        String tenNgonNgu = txtTenNgonNgu.getText();
        ET_NgonNgu et = new ET_NgonNgu(maNgonNgu, tenNgonNgu);
        if (maNgonNgu == "" || tenNgonNgu == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                bll.suaNgonNgu(et);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                reset();
            } catch (SQLException ex) {
                Logger.getLogger(frmNgonNgu.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Sửa không thành công");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        String maNgonNgu = txtMaNgonNgu.getText();
        String tenNgonNgu = txtTenNgonNgu.getText();
        ET_NgonNgu et;

        int row = tblNgonNgu.getSelectedRow();
        if (row >= 0) {
            et = new ET_NgonNgu(maNgonNgu, tenNgonNgu);
            try {
                if (bll.xoaNgonNgu(et)) {
                    JOptionPane.showMessageDialog(rootPane, "Xoá không thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    reset();
                }

            } catch (SQLException ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngôn ngữ");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed

        try {
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(frmNgonNgu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnMoiActionPerformed
    private void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblNgonNgu.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã ngôn ngữ");
        model.addColumn("Tên ngôn ngữ");
        tblNgonNgu.setModel(model);
    }

    public void hienThiNN() throws SQLException {
        ResultSet rs = bll.layNgonNgu();
        DefaultTableModel model = (DefaultTableModel) tblNgonNgu.getModel();
        model.setNumRows(0);
        while (rs.next()) {
            Object[] col = new Object[2];
            for (int i = 1; i <= 2; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
        tblNgonNgu.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tblNgonNgu.getSelectedRow() >= 0) {
                    txtMaNgonNgu.setText(tblNgonNgu.getValueAt(tblNgonNgu.getSelectedRow(), 0) + "");
                    txtTenNgonNgu.setText(tblNgonNgu.getValueAt(tblNgonNgu.getSelectedRow(), 1) + "");
                }
            }
        });
    }

    public void reset() throws SQLException {
        ResultSet rs = bll.layNgonNgu();
        rs.last();
        int row = rs.getRow();
        if (row == 0) {
            STT = 1;
        } else {
            rs.beforeFirst();
            while (rs.next()) {
                STT = Integer.parseInt(rs.getObject(1).toString().substring(2)) + 1;
            }
        }
        String ma = String.format("%02d", STT);
        txtMaNgonNgu.setText("NN" + ma);
        hienThi();
        hienThiNN();
        txtTenNgonNgu.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNgonNgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNgonNgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNgonNgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNgonNgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmNgonNgu().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmNgonNgu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNgonNgu;
    private javax.swing.JTextField txtMaNgonNgu;
    private javax.swing.JTextField txtTenNgonNgu;
    // End of variables declaration//GEN-END:variables
}
