/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.BLL_TheThuVien;
import bll.BLL_NhanVien;
import et.ET_TheThuVien;
import et.ET_DocGia;
import bll.BLL_DocGia;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class frmTheThuVien extends javax.swing.JFrame {

    private BLL_TheThuVien bllThe;
    private BLL_NhanVien bllNV;
    private BLL_DocGia bllDG;

    /**
     * Creates new form frmTheThuVien
     */
    public frmTheThuVien() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        bllThe = new BLL_TheThuVien();
        bllNV = new BLL_NhanVien();
        bllDG = new BLL_DocGia(); 
        ResultSet rs = bllNV.layNV();
        
        comboboxNV();
        hienThi();
        hienThiThe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtNgayLap = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTV = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        txtMaDocGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dtNgayLap.setBackground(new java.awt.Color(155, 177, 255));

        jPanel2.setBackground(new java.awt.Color(84, 101, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THẺ THƯ VIỆN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(384, 384, 384))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã thẻ thư viện");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã độc giả");

        tblTTV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblTTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Mã thẻ thư viện", "Họ", "Tên", "Giới tính", "Số điện thoại", "Ngày sinh", "Ngày đăng ký"
            }
        ));
        tblTTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTTV);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nhân Viên Lập");

        cbMaNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huỳnh Thị Ngọc Thư", "Bùi Hồng Ngọc" }));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_26px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_remove_26px_1.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_26px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Họ độc giả");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên độc giả");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Ngày sinh");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Giới tính");

        rdNam.setText("Nam ");

        rdNu.setText("Nu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Số CCCD");

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dtNgayLapLayout = new javax.swing.GroupLayout(dtNgayLap);
        dtNgayLap.setLayout(dtNgayLapLayout);
        dtNgayLapLayout.setHorizontalGroup(
            dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dtNgayLapLayout.createSequentialGroup()
                            .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dtNgayLapLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)))
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dtNgayLapLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dtNgayLapLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(rdNam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdNu))
                        .addGroup(dtNgayLapLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(104, 104, 104)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnThoat)
                .addGap(133, 133, 133))
            .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dtNgayLapLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );
        dtNgayLapLayout.setVerticalGroup(
            dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel10)
                        .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(rdNam)
                    .addComponent(rdNu)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnThoat)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addContainerGap(366, Short.MAX_VALUE))
            .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dtNgayLapLayout.createSequentialGroup()
                    .addGap(444, 444, 444)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maThe = txtMaThe.getText();
        String maDG = txtMaDocGia.getText();
        Date ngaySinh = dtNgaySinh.getDate();
        String tinhTrang = "Con han";
        String nhanVien = null;
        try {
            nhanVien = bllNV.layMa(cbMaNV.getSelectedItem().toString());
        } catch (Exception ex) {
            Logger.getLogger(frmTheThuVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        int slSach = 3;
        String ho = txtHo.getText();
        String ten = txtTen.getText();
        String diaChi = txtDiaChi.getText();
        int trangThaiThe = 1;
        String gioiTinh = "Nam";
        if(rdNam.isSelected()){
            gioiTinh = rdNam.getText();
        }else
        {
            gioiTinh = rdNu.getText();
        }
        String CCCD = txtCCCD.getText();
        ET_TheThuVien et;
        ET_DocGia etdg;
        if (txtMaDocGia.getText().compareTo("") > 0 || txtTen.getText().compareTo("") > 0 || txtHo.getText().compareTo("") > 0 || txtDiaChi.getText().compareTo("") > 0 || txtCCCD.getText().compareTo("") > 0 ) {
            
             try {
                if( bllDG.checkTT(CCCD)== true ){
                    JOptionPane.showMessageDialog(null, "Độc giả đã tồn tại");
                }else{
                    if(bllThe.checkTT(maThe) == true)
                    {
                        JOptionPane.showMessageDialog(null, "Thẻ đã tồn tại");
                    }else{
                        etdg = new ET_DocGia(maDG, ho, ten, ngaySinh, gioiTinh,CCCD,diaChi , trangThaiThe);
                        et = new ET_TheThuVien(maThe,maDG,slSach,nhanVien, tinhTrang);              
                        if (bllDG.themDG(etdg) == true ) {
                            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                           
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
                        }
                        bllThe.themThe(et);
                        reset();
                        hienThiThe();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(frmTheThuVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
           JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        }
       
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
        String maDG = txtMaDocGia.getText();
        String ho = txtHo.getText();
        String ten = txtTen.getText();
        Date ngaySinh = dtNgaySinh.getDate();
        int trangThai = 1;
        String diaChi = txtDiaChi.getText();
        String gioiTinh = "Nam";
        if(rdNam.isSelected()){
            gioiTinh = rdNam.getText();
        }else
        {
            gioiTinh = rdNu.getText();
        }
        String CCCD = txtCCCD.getText();
        int row = tblTTV.getSelectedRow();
        if (row >= 0) {
            ET_DocGia et = new ET_DocGia(maDG, ho, ten, ngaySinh, gioiTinh, CCCD, diaChi,trangThai);
            try {
                if (bllDG.xoaThe(et)) {
                    JOptionPane.showMessageDialog(rootPane, "Thành công");
                    reset();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Không thành công");
                }
                hienThiThe();
            } catch (Exception ex) {
               ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn !");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblTTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTTVMouseClicked
        // TODO add your handling code here:
        String gt = "Nam";
         int row = tblTTV.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblTTV.getModel();
        txtMaDocGia.setText(model.getValueAt(row, 1).toString());
        txtMaThe.setText(model.getValueAt(row, 0).toString());
        txtHo.setText(model.getValueAt(row, 2).toString());
        txtTen.setText(model.getValueAt(row, 3).toString());
        txtCCCD.setText(model.getValueAt(row,4 ).toString());
        if(gt.compareTo(model.getValueAt(row, 5).toString()) == 0){
           rdNam.setSelected(true);
           rdNu.setSelected(false);
        }else{
            rdNu.setSelected(true);
            rdNam.setSelected(false);
        }
        dtNgaySinh.setDate((Date) model.getValueAt(row, 6));
        txtDiaChi.setText(model.getValueAt(row, 7).toString());
        
        try {
            cbMaNV.setSelectedItem(bllNV.layTen(model.getValueAt(row, 9).toString()));

        } catch (Exception ex) {
            Logger.getLogger(frmCapNhatSach.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tblTTVMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            // TODO add your handling code here:
            reset();
        } catch (Exception ex) {
            Logger.getLogger(frmDanhMuc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMoiActionPerformed
//    public void layMa() throws Exception {
//        ResultSet rs = bllThe.layDSThe();
//        rs.last();
//        // JOptionPane.showMessageDialog(null, rs.getRow());
//        int row = rs.getRow();
//        if (row == 0) {
//            STT = 1;
//        } else {
//            rs.beforeFirst();
//            while (rs.next()) {
//                STT = Integer.parseInt(rs.getObject(1).toString().substring(3)) + 1;
//            }
//        }
//        String ma = String.format("%02d", STT);
//        txtMaThe.setText("TTV" + ma);
//        txtMaDocGia.setText("");
//        txtHo.setText("");
//        txtTen.setText("");
//        txtCCCD.setText("");
//        txtDiaChi.setText("");
//        txtMaDocGia.requestFocus();
//    }
    public void reset() {
        txtMaThe.setText("");
        txtMaDocGia.setText("");
        txtCCCD.setText("");
        txtDiaChi.setText("");
        txtHo.setText("");
        dtNgaySinh.setDate(new Date());
        txtTen.setText("");
        cbMaNV.setSelectedIndex(0);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTheThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTheThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTheThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTheThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new frmTheThuVien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmTheThuVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void comboboxNV() throws Exception {
        bllNV = new BLL_NhanVien();
        cbMaNV.removeAllItems();
        ResultSet rs = bllNV.layNV();
        while (rs.next()) {
            cbMaNV.addItem(rs.getString("firstname"));
        }
    }
    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblTTV.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã Thẻ");
        model.addColumn("Mã độc giả");
        model.addColumn("Họ");
        model.addColumn("Tên");
        model.addColumn("cccd");
        model.addColumn("Giới Tính");
        model.addColumn("Ngày sinh");
        model.addColumn("Địa chỉ");
        model.addColumn("Ngày lập thẻ");
        model.addColumn("Nhân viên tạo");
        model.addColumn("Tình trạng");
        tblTTV.setModel(model);
    }

    public void hienThiThe() throws SQLException {
        ResultSet rs = bllThe.layDSThe();
        DefaultTableModel model = (DefaultTableModel) tblTTV.getModel();
        model.setRowCount(0);
        while (rs.next()) {
            Object[] col = new Object[11];
            for (int i = 1; i <= 11; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JPanel dtNgayLap;
    private com.toedter.calendar.JDateChooser dtNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblTTV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
