/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import bll.BLL_TheThuVien;
import bll.BLL_NhanVien;
import et.ET_TheThuVien;
import et.ET_DocGia;
import bll.BLL_DocGia;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import bll.BLL_LoaiDocGia;
import et.ET_LoaiDocGia;
import et.ET_NhanVien;
import javax.swing.DefaultComboBoxModel;
import java.util.Date;

/**
 *
 * @author yushu
 */
import java.text.SimpleDateFormat;
import java.util.Calendar;

public class frmTheThuVien extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTheThuVien
     */
    private BLL_TheThuVien bllThe;
    private BLL_NhanVien bllNV;
    private BLL_DocGia bllDG;
    private BLL_LoaiDocGia bllLoaiDG;
    private int STT = 0;

    public frmTheThuVien() throws Exception {
        initComponents();
        this.setTitle("Quản lý thẻ thư viện");
        bllThe = new BLL_TheThuVien();
        bllNV = new BLL_NhanVien();
        bllDG = new BLL_DocGia();
        bllLoaiDG = new BLL_LoaiDocGia();
        ResultSet rs = bllNV.layNV();
        // hiển thị combobox độc giả
        loadCboLoaiDocGia();
        // hiển thị combobox nhân viên
        comboboxNV();
        // hiển thị ds thẻ thư viện lên table
        reset();

    }

    public void loadCboLoaiDocGia() throws SQLException, Exception {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ResultSet rs = null;
        rs = bllLoaiDG.layDS();
        while (rs.next()) {
            ET_LoaiDocGia et = new ET_LoaiDocGia(rs.getInt(1), rs.getString(2), rs.getInt(3), rs.getInt(4));
            model.addElement(et);
        }
        cboLoaiDocGia.setModel(model);
    }

    // Load combo nhân viên
    public void comboboxNV() throws Exception {
        bllNV = new BLL_NhanVien();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ResultSet rs = bllNV.layNV();
        while (rs.next()) {
            String ngSIinh = rs.getString(6).toString();
            Date ngSinh = new SimpleDateFormat("yyyy-MM-dd").parse(ngSIinh);
            ET_NhanVien et = new ET_NhanVien(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), ngSinh, rs.getString(7));
            model.addElement(et);
        }
        cbMaNV.setModel(model);
    }

    // set column cho model
    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblTTV.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã Thẻ");
        model.addColumn("Họ");
        model.addColumn("Tên");
        model.addColumn("cccd");
        model.addColumn("Giới Tính");
        model.addColumn("Ngày sinh");
        model.addColumn("Địa chỉ");
        model.addColumn("Ngày lập thẻ");
        model.addColumn("Nhân viên tạo");
        model.addColumn("Hạn thẻ");
        tblTTV.setModel(model);
    }

    // hiển thị danh sách thẻ thư viện lên table
    public void hienThiThe() throws SQLException {
        ResultSet rs = bllThe.layDSThe();
        DefaultTableModel model = (DefaultTableModel) tblTTV.getModel();
        model.setRowCount(0);
        while (rs.next()) {
            Object[] col = new Object[10];
            for (int i = 1; i <= 10; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
    }

    // reset các fields
    public void reset() throws Exception {
        txtMaThe.setText(layMaTheTV());
        txtMaThe.setEditable(false);
        txtCCCD.setText("");
        txtDiaChi.setText("");
        txtHo.setText("");
        dtNgaySinh.setDate(new Date());
        txtTen.setText("");
        cbMaNV.setSelectedIndex(0);
        rdNam.setSelected(true);
        hienThi();
        hienThiThe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtNgayLap = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dtNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTV = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cboLoaiDocGia = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        btnThoat = new javax.swing.JButton();

        dtNgayLap.setBackground(new java.awt.Color(155, 177, 255));

        jPanel2.setBackground(new java.awt.Color(84, 101, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THẺ THƯ VIỆN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1))
        );

        txtMaThe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã thẻ thư viện");

        dtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblTTV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã độc giả", "Mã thẻ thư viện", "Họ", "Tên", "Giới tính", "Số điện thoại", "Ngày sinh", "Ngày đăng ký"
            }
        ));
        tblTTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTTV);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nhân Viên Lập");

        cbMaNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huỳnh Thị Ngọc Thư", "Bùi Hồng Ngọc" }));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_26px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Họ độc giả");

        txtHo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên độc giả");

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Ngày sinh");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Giới tính");

        rdNam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdNam.setText("Nam ");
        rdNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdNamMouseClicked(evt);
            }
        });

        rdNu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdNu.setText("Nu");
        rdNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdNuMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Số CCCD");

        txtCCCD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCCCD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCCCDFocusLost(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_new_26px_4.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Loại độc giả");

        cboLoaiDocGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboLoaiDocGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huỳnh Thị Ngọc Thư", "Bùi Hồng Ngọc" }));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_26px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dtNgayLapLayout = new javax.swing.GroupLayout(dtNgayLap);
        dtNgayLap.setLayout(dtNgayLapLayout);
        dtNgayLapLayout.setHorizontalGroup(
            dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(101, 101, 101)
                        .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(113, 113, 113)
                        .addComponent(rdNam)
                        .addGap(79, 79, 79)
                        .addComponent(rdNu))
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(64, 64, 64)
                        .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnThoat))
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(jLabel13)
                .addGap(82, 82, 82)
                .addComponent(cboLoaiDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dtNgayLapLayout.setVerticalGroup(
            dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtNgayLapLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdNam, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdNu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9))
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtNgayLapLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13))
                    .addComponent(cboLoaiDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(dtNgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnThoat)
                    .addComponent(btnMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTTVMouseClicked
        // TODO add your handling code here:
        String gt = "Nam";
        int row = tblTTV.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblTTV.getModel();
        txtMaThe.setText(model.getValueAt(row, 0).toString());
        txtHo.setText(model.getValueAt(row, 1).toString());
        txtTen.setText(model.getValueAt(row, 2).toString());
        txtCCCD.setText(model.getValueAt(row, 3).toString());
        if (gt.compareTo(model.getValueAt(row, 4).toString()) == 0) {
            rdNam.setSelected(true);
            rdNu.setSelected(false);
        } else {
            rdNu.setSelected(true);
            rdNam.setSelected(false);
        }
        dtNgaySinh.setDate((Date) model.getValueAt(row, 5));
        txtDiaChi.setText(model.getValueAt(row, 6).toString());

        try {
            cbMaNV.setSelectedItem(bllNV.layTen(model.getValueAt(row, 7).toString()));

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_tblTTVMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // Mã thẻ thư viện
        String maThe = txtMaThe.getText();
        // Mã độc giả
        String maDG = "";
        try {
            maDG = layMaDG();
        } catch (Exception ex) {
            Logger.getLogger(frmTheThuVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Ngày sinh
        Date ngaySinh = dtNgaySinh.getDate();
        String nhanVien = null;
        try {
            ET_NhanVien nv = (ET_NhanVien) cbMaNV.getSelectedItem();
            nhanVien = nv.getMaNhanVien();
        } catch (Exception ex) {
            Logger.getLogger(frmTheThuVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Họ độc giả
        String ho = txtHo.getText();
        // Tên độc giả
        String ten = txtTen.getText();
        // Địa chỉ
        String diaChi = txtDiaChi.getText();
        // Giới tính
        String gioiTinh = "Nam";
        if (rdNam.isSelected()) {
            gioiTinh = rdNam.getText();
        } else {
            gioiTinh = rdNu.getText();
        }
        // Căn cước công dân
        String CCCD = txtCCCD.getText();
        // Đối tượng thẻ thư viện
        ET_TheThuVien et;

        // Đối tượng độc giả
        ET_DocGia etdg;
        if (maThe.compareTo("") == 0 || ten.compareTo("") == 0 || ho.compareTo("") == 0 || diaChi.compareTo("") == 0 || CCCD.compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");

        } else {
            try {
                if (bllThe.checkTT(maThe) == true) {
                    JOptionPane.showMessageDialog(null, "Thẻ đã tồn tại");
                } else {
                    if (bllDG.checkTT(CCCD) == true) {
                        JOptionPane.showMessageDialog(null, "Độc giả đã tồn tại, vui lòng gia gia hạn thẻ?");

                    } else {
                        // Đối tượng loại độc giả
                        ET_LoaiDocGia etLoaiDG = (ET_LoaiDocGia) cboLoaiDocGia.getSelectedItem();
                        // Lấy mã loại độc giả
                        int loaiDocGia = etLoaiDG.getMaLoai();
                        etdg = new ET_DocGia(maDG, ho, ten, ngaySinh, gioiTinh, CCCD, diaChi, loaiDocGia);
                        Calendar cal = Calendar.getInstance();
                        // Ngày tạo thẻ
                        Date ngTao = cal.getTime();
                        cal.add(Calendar.YEAR, 1);
                        // Ngày hết hạn thẻ
                        Date ngayHetHan = cal.getTime();
                        et = new ET_TheThuVien(maThe, maDG, nhanVien, ngTao, ngayHetHan);
                        boolean kq = true;
                        kq = bllDG.themDG(etdg);
                        kq = false;

                        kq = bllThe.themThe(et);
                        if (kq) {
                            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                            reset();
                            hienThiThe();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
                        }

                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            // TODO add your handling code here:
            reset();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void txtCCCDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCCCDFocusLost
        // TODO add your handling code here:
        String cccd = txtCCCD.getText();
        try {
            if (bllDG.checkTT(cccd)) {
                JOptionPane.showMessageDialog(null, "Độc giả đã tồn tại, vui lòng gia gia hạn thẻ?");
            }
        } catch (Exception ex) {
            Logger.getLogger(frmTheThuVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtCCCDFocusLost

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void rdNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNamMouseClicked
        // TODO add your handling code here:
        rdNu.setSelected(false);
    }//GEN-LAST:event_rdNamMouseClicked

    private void rdNuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNuMouseClicked
        // TODO add your handling code here:
        rdNam.setSelected(false);
    }//GEN-LAST:event_rdNuMouseClicked

    // Lấy mã độc giả
    public String layMaDG() throws Exception {
        STT = 0;
        ResultSet rs = bllDG.layDS();
        rs.last();
        // JOptionPane.showMessageDialog(null, rs.getRow());
        int row = rs.getRow();
        if (row == 0) {
            STT = 1;
        } else {
            rs.beforeFirst();
            while (rs.next()) {
                STT = Integer.parseInt(rs.getObject(1).toString().substring(2)) + 1;
            }
        }
        String ma = String.format("%03d", STT);
        return "DG" + ma;
    }

    // Lấy mã thẻ thư viện
    public String layMaTheTV() throws Exception {
        STT = 0;
        ResultSet rs = bllDG.layDS();
        rs.last();
        // JOptionPane.showMessageDialog(null, rs.getRow());
        int row = rs.getRow();
        if (row == 0) {
            STT = 1;
        } else {
            rs.beforeFirst();
            while (rs.next()) {
                STT = Integer.parseInt(rs.getObject(1).toString().substring(2)) + 1;
            }
        }
        String ma = String.format("%03d", STT);
        return "TTV" + ma;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JComboBox<String> cboLoaiDocGia;
    private javax.swing.JPanel dtNgayLap;
    private com.toedter.calendar.JDateChooser dtNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblTTV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
