/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import bll.BLL_TraSachh;
import et.ET_TraSachh;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yushu
 */
public class frmTraSach extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTra
     */
    private BLL_TraSachh bll;
    HashMap<String, String> hm_nv = new HashMap<String, String>();
    private Boolean kq = false;

    public frmTraSach() throws Exception {
        initComponents();
        this.setTitle("Trả sách");
        bll = new BLL_TraSachh();

        hienThi();
        hienThiTraSach();

        txtMaSach.setEditable(false);
        txtSoNgayQuaHan.setEditable(false);
        dtpNgayThucTra.setEnabled(false);
        dtpNgayDuKienTra.setEnabled(false);
        txtDocGia.setEditable(false);
        txtMaTheThuVien.setEditable(false);
        //txtTienPhat.setEditable(false);

        // lấy ngày hiện tại 
        Date date = new Date();
        dtpNgayThucTra.setDate(date);

        this.bll = new BLL_TraSachh();
        this.hm_nv = bll.hm_NV();
        loadCBNV();
    }

    public void loadCBNV() {

        cbbNhanVien.removeAllItems();
        Map<String, String> map = new TreeMap<>(hm_nv);

        for (Map.Entry<String, String> entry : map.entrySet()) {
            Object value = entry.getValue();
            cbbNhanVien.addItem(value.toString());
        }
    }

    public String getMaNV() {
        for (Map.Entry<String, String> entry : hm_nv.entrySet()) {
            if (entry.getValue().equals(cbbNhanVien.getSelectedItem())) {
                return entry.getKey();
            }
        }
        return "";
    }

    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblTraSach.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Mã trả sách");
        model.addColumn("Mã mượn sách");
        model.addColumn("Ngày dự trả");
        model.addColumn("Ngày thực trả");
        model.addColumn("Mã sách");
        model.addColumn("Tên đọc giả");
        model.addColumn("Mã thẻ thư viện");
        model.addColumn("Số ngày quá hạn");
        model.addColumn("Tiền phạt");
        model.addColumn("Mã nhân viên");
        model.addColumn("Tình trạng sách");
        tblTraSach.setModel(model);
    }

    public void hienThiTraSach() throws SQLException {

        DefaultTableModel model = (DefaultTableModel) tblTraSach.getModel();
        model.setRowCount(0);
        ResultSet rs = bll.layTraSach();

        while (rs.next()) {
            Object[] col = new Object[10];
            for (int i = 1; i <= 10; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
    }

    public void soNgayQuaHan() {
        SimpleDateFormat fr = new SimpleDateFormat("yyyy-MM-dd");
        Date ngayDuKienTra = null;
        Date ngayTra = null;

        try {
            if (kq) {
                ngayTra = fr.parse(fr.format(dtpNgayThucTra.getDate()));
                ngayDuKienTra = fr.parse(fr.format(dtpNgayDuKienTra.getDate()));
                int datediff = (int) (ngayTra.getTime() - ngayDuKienTra.getTime());
                int days = datediff / (60 * 60 * 1000) / 24;
                if (days < 0) {
                    txtSoNgayQuaHan.setText("0");
                } else {
                    txtSoNgayQuaHan.setText(Long.toString(days));
                }
            } else {
                txtSoNgayQuaHan.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoNgayQuaHan = new javax.swing.JTextField();
        txtMaMuonSach = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraSach = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        dtpNgayThucTra = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaTinhTrangSach = new javax.swing.JTextArea();
        txtMaSach = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dtpNgayDuKienTra = new com.toedter.calendar.JDateChooser();
        txtDocGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaTheThuVien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        btnMoi = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(155, 177, 255));

        jPanel2.setBackground(new java.awt.Color(84, 101, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TRẢ SÁCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel1)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã mượn sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ngày thực trả");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã sách");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nhân viên");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Số ngày quá hạn");

        txtSoNgayQuaHan.setMinimumSize(new java.awt.Dimension(7, 28));
        txtSoNgayQuaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNgayQuaHanActionPerformed(evt);
            }
        });

        txtMaMuonSach.setMinimumSize(new java.awt.Dimension(7, 28));
        txtMaMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMuonSachActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_26px.png"))); // NOI18N
        btnLuu.setText("LƯU");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        tblTraSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTraSach);

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shutdown_26px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        dtpNgayThucTra.setDateFormatString("dd/MM/yyyy");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tình trạng sách");

        txtaTinhTrangSach.setColumns(20);
        txtaTinhTrangSach.setRows(5);
        jScrollPane2.setViewportView(txtaTinhTrangSach);

        txtMaSach.setMinimumSize(new java.awt.Dimension(7, 28));
        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_26px.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ngày dự trả");

        dtpNgayDuKienTra.setDateFormatString("dd/MM/yyyy");

        txtDocGia.setMinimumSize(new java.awt.Dimension(7, 28));
        txtDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocGiaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Tên độc giả");

        txtMaTheThuVien.setMinimumSize(new java.awt.Dimension(7, 28));
        txtMaTheThuVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTheThuVienActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Mã thẻ thư viện");

        cbbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhanVienActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_new_26px_4.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(txtMaMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnTim)
                .addGap(99, 99, 99)
                .addComponent(jLabel9)
                .addGap(47, 47, 47)
                .addComponent(txtDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(56, 56, 56)
                .addComponent(dtpNgayDuKienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(jLabel10)
                .addGap(15, 15, 15)
                .addComponent(txtMaTheThuVien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(dtpNgayThucTra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(txtSoNgayQuaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addComponent(jLabel7)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLuu)
                .addGap(27, 27, 27)
                .addComponent(btnThoat))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(txtMaMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaTheThuVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(dtpNgayDuKienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpNgayThucTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(txtSoNgayQuaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoNgayQuaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNgayQuaHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNgayQuaHanActionPerformed

    private void txtMaMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMuonSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMuonSachActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String maMuon = txtMaMuonSach.getText();
        java.sql.Date ngayDuTra = new java.sql.Date(dtpNgayDuKienTra.getDate().getTime());
        java.sql.Date ngayThucTra = new java.sql.Date(dtpNgayThucTra.getDate().getTime());
        String maSach = txtMaSach.getText();
        String tenDocGia = txtDocGia.getText();
        String maThuVien = txtMaTheThuVien.getText();
        String soNgayQuaHan = txtSoNgayQuaHan.getText();
        String maNhanVien = getMaNV();
        String tinhTrangSach = txtaTinhTrangSach.getText();

        ET_TraSachh et = new ET_TraSachh(Integer.parseInt(maMuon), ngayDuTra, ngayThucTra, maSach, tenDocGia, maThuVien, Integer.parseInt(soNgayQuaHan), maNhanVien, tinhTrangSach);

        try {
            if (bll.themTraSach(et)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
        }
        try {
            hienThiTraSach();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed

        try {
            ResultSet rs = bll.timTraSach(txtMaMuonSach.getText());
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã mượn sách");
                txtMaMuonSach.setText("");
                txtMaSach.setText("");
                txtDocGia.setText("");
                txtaTinhTrangSach.setText("");
                txtMaTheThuVien.setText("");
                txtSoNgayQuaHan.setText("");
                kq = false;
                dtpNgayDuKienTra.setDate(null);
            } else {
                txtMaMuonSach.setText(rs.getString("id_rental_detail"));
                dtpNgayDuKienTra.setDate(rs.getDate("return_date"));
                txtMaSach.setText(rs.getString("id_book"));
                txtMaTheThuVien.setText(rs.getString("id_lib_card"));
                kq = true;
                try {
                    String rs1 = bll.layTenDocGia(txtMaTheThuVien.getText());
                    txtDocGia.setText(rs1);
                } catch (Exception ex) {
                  ex.printStackTrace();
                }
                txtaTinhTrangSach.setText(rs.getString("status"));
            }
        } catch (Exception e) {
        }
        soNgayQuaHan();
        //tienPhat();
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocGiaActionPerformed

    private void txtMaTheThuVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTheThuVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheThuVienActionPerformed

    private void cbbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhanVienActionPerformed

    }//GEN-LAST:event_cbbNhanVienActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        txtMaSach.setText("");
        dtpNgayDuKienTra.setDate(new Date());
        dtpNgayThucTra.setDate(new Date());
        txtMaSach.setText("");
        cbbNhanVien.setSelectedIndex(0);
        txtMaTheThuVien.setText("");
        txtDocGia.setText("");
        txtSoNgayQuaHan.setText("");
        txtaTinhTrangSach.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private com.toedter.calendar.JDateChooser dtpNgayDuKienTra;
    private com.toedter.calendar.JDateChooser dtpNgayThucTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTraSach;
    private javax.swing.JTextField txtDocGia;
    private javax.swing.JTextField txtMaMuonSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtMaTheThuVien;
    private javax.swing.JTextField txtSoNgayQuaHan;
    private javax.swing.JTextArea txtaTinhTrangSach;
    // End of variables declaration//GEN-END:variables
}
